Authentication/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout, name='logout'),
]

RegisterationSample/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('Authentication.urls')),
    path('panel/', include('panel.urls'))
]

panel/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('', PanelView.as_view(), name='panel'),
    path('user/<int:pk>/edit', UserUpdateView.as_view(), name='user_edit'),
    path('API/user/<int:pk>/', UserDetail.as_view(), name='user_detail')
]

Authentication/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50, null=False)
    last_name = models.CharField(max_length=50, blank=True)
    email = models.EmailField(null=False, unique=True, error_messages={'unique': 'کاربر با ایمیل وارد شده وجود دارد'})
    phone = models.CharField(max_length=14, null=False, unique=True, error_messages={'unique': 'کاربر با شماره تلفن وارد شده وجود دارد'})
    date_joined = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    objects = CustomUserManager()

    class Meta:
        db_table = 'user'

Authentication/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(label="نام", max_length=50, min_length=4,
                                 widget=forms.TextInput(attrs={"placeholder": "نام", 'class': 'form-control'}),
                                 required=True)
    last_name = forms.CharField(label="نام خانوادگی", max_length=50, min_length=4,
                                widget=forms.TextInput(attrs={"placeholder": "نام خانوادگی", 'class': 'form-control'}),
                                required=False)
    email = forms.EmailField(label='ایمیل', widget=forms.EmailInput(attrs={"placeholder": "ایمیل", 'class': 'form-control'}))
    phone = forms.CharField(label="شماره همراه", max_length=11,
                            widget=forms.TextInput(attrs={"placeholder": "شماره همراه: ", 'class': 'form-control'}),
                            validators=[RegexValidator(
                                regex=r'^09\d{9}$',  # Pattern for Iranian phone number format
                                message='شماره تماس صحیح 09106956260',
                                code='invalid_phone_number'
                            )],
                            required=True)
    password1 = forms.CharField(label="رمز عبور",
                                widget=forms.PasswordInput(attrs={"placeholder": "رمز عبور", 'class': 'form-control'}),
                                required=True)
    password2 = forms.CharField(label="تکرار رمز عبور", required=True,
                                widget=forms.PasswordInput(attrs={"placeholder": "تکرار رمز عبور", 'class': 'form-control'}))

    error_messages = {'password_mismatch': "رمز عبور تایید نشد"}

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")

        if password != password_confirm:
            raise forms.ValidationError("Passwords do not match. Please enter matching passwords for New Password and "
                                        "Confirm New Password.")

        return cleaned_data

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'phone']


class UserLoginForm(forms.Form):
    email = forms.EmailField(label='ایمیل', widget=forms.EmailInput(attrs={"placeholder": "ایمیل", 'class': 'form-control'}), required=True)
    password = forms.CharField(label="رمز عبور", widget=forms.PasswordInput(attrs={"placeholder": "رمز عبور", 'class': 'form-control'}),
                               required=True)

Authentication/views.py
from django.shortcuts import render, redirect
from rest_framework.views import APIView
from .forms import UserRegisterForm, UserLoginForm
from django.contrib.auth import login as auth_login, logout as auth_logout, authenticate
from django.contrib import messages
from .authentication import admin_authentication


class RegistrationView(APIView):
    def get(self, request):
        reg_form = UserRegisterForm()
        login_form = UserLoginForm
        return render(request, 'authentication/authentication.html',
                      {'reg_form': reg_form, 'login_form': login_form, 'default': 'registration'})

    def post(self, request):
        reg_form = UserRegisterForm(request.POST)
        if reg_form.is_valid():
            reg_form.save()
            return redirect('login')
        else:
            login_form = UserLoginForm
            return render(request, 'authentication/authentication.html',
                          {'reg_form': reg_form, 'login_form': login_form, 'default': 'registration'})


class LoginView(APIView):
    def get(self, request):
        login_form = UserLoginForm()
        reg_form = UserRegisterForm
        return render(request, 'authentication/authentication.html',
                      {'reg_form': reg_form, 'login_form': login_form, 'default': 'login'})

    def post(self, request):
        login_form = UserLoginForm(request.POST)
        if login_form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)
            if user:
                if admin_authentication(user):
                    auth_logout(request)
                    auth_login(request, user)
                    return redirect('panel')
                else:
                    messages.error(request, 'شما به پنل دسترسی ندارید')
                    return redirect('login')
            else:
                messages.error(request, 'ایمیل یا رمز عبور صحیح نمی‌باشد')
                return redirect('login')
        else:
            messages.error(request, 'ایمیل یا رمز عبور صحیح نمی‌باشد')
            return redirect('login')


def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
        return redirect('login')
    else:
        return redirect('login')

templates/authentication/authentication.html
{% extends 'layout/layout.html' %}

{% load static %}

{% block style %}
    <style>
        .errorlist{
            margin-bottom: 0;
        }
        .errorlist li{
            color: orangered;
        }
    </style>
{% endblock %}

{% block main %}
    <div class="container-fluid vh-100 d-flex justify-content-center align-items-center">
        <div class="col-10 col-md-8 col-lg-5">
            <div class="text-center mb-5">
                <h4>Welcome To</h4>
                <h1>Aranic</h1>
            </div>
            <div class="rounded-4 shadow-lg">
                <div class="col-12 d-flex">
                    <div class="col-6 text-center rounded-top-4 {% if default == 'login' %}bg-light shadow{% endif %}">
                        <button id="registrationBtn" class="col-12 btn">
                            ثبت نام
                        </button>
                    </div>
                    <div class="col-6 text-center rounded-top-4 {% if default == 'registration' %}bg-light shadow{% endif %}">
                        <button id="loginBtn" class="col-12 btn">
                             ورود به پنل
                        </button>
                    </div>
                </div>
                <div class="col-12 px-5 py-2">
                    <form id="registerForm" action="{% url 'registration' %}" method="post" class="{% if default == 'login' %}d-none{% endif %}">
                        {% csrf_token %}
                        {{ reg_form.as_p }}
                        <div class="mt-3 d-flex justify-content-center">
                            <button class="col-10 col-sm-8 col-md-6 col-lg-5 btn btn-success" type="submit">ثبت‌ نام</button>
                        </div>
                    </form>
                    <form id="loginForm" action="{% url 'login' %}" method="post" class="my-3 {% if default == 'registration' %}d-none{% endif %}">
                        {% if messages %}
                            {% for message in messages %}
                            <p class="text-danger">{{ message }}</p>
                            {% endfor %}
                        {% endif %}
                        {% csrf_token %}
                        <p>
                            <label for="id_first_name">{{ login_form.email.label }}:</label>
                                {{ login_form.email }}
                        </p>
                        <p>
                            <label for="id_first_name">{{ login_form.password.label }}:</label>
                                {{ login_form.password }}
                        </p>
                        <div class="m-4 d-flex justify-content-center">
                            <button class="col-10 col-sm-8 col-md-6 col-lg-5 btn btn-primary" type="submit">ورود</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
<script src="{% static 'authentication.js'%}"></script>
{% endblock %}